[package]
name = "webserver"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.8.1"
env_logger = "0.11.6"
http-body-util = "0.1.0"
log = "0.4.25"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.5.2", features = ["util"]}
